api/urls.py
from django.urls import path, include
from .views import ProductApiView

urlpatterns = [
    path('', ProductApiView.as_view()),
]

basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', views.basket_remove, name='basket_remove'),
]

selection/urls.py
from django.urls import path

from .views import product_list, product_detail

app_name = 'selection'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>', product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', product_detail, name='product_detail'),
]

store_for_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls


from django.views.generic.base import TemplateView
from django.conf import settings


#schema_view = get_schema_view(title="Store_for_all")
schema_view = get_swagger_view(title="Store_for_all")


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('selection/', include('selection.urls', namespace='selection')),
    path('orders', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls')),
    #path('schema/', schema_view),
    path('docs/', include_docs_urls(title="Store_for_all")),
    path('swagger-docs/', schema_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-
awesome/5.13.0/css/all.min.css">
    <title>Store_For_All</title>
  </head>

<style>

    html {
   margin: 0px;
   height: 100%;
   width: 100%;
}

body {
   margin: 0px;
   min-height: 100%;
   width: 100%;
}
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
    height: auto;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
.topnav a.bt{
    float: right;
    padding: 6px;
    border: none;
    margin-top: 8px;
    margin-right: 16px;
    font-size: 17px;
}
</style>
</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'selection:product_list' %}">Store_For_All</a>
                {% for category in categories %}
                    <div class="container-xxl ">
                        {% if category.slug == requested_category.slug %}
                        {% else %}
                            <a href="{{ category.get_absolute_urls }}">
                                {{ category.name }}
                            </a>
                        {% endif %}
                    </div>
                {% endfor %}
<a href="{% url 'login' %}" class="bt">Login</a>
<a href="{% url 'signup' %}" class="bt">Signup</a>
<a href="{% url 'basket:basket_detail' %}"
                           class="nav-link text-red drop-btn">
                            <i class="fas fa-shopping-cart"></i>
                            $<span id="cart_price">{{ basket_total_price|floatformat:2 }}</span>
                        </a>
</div>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<style>

* {
    box-sizing: border-box;
}
body {
  background-image: url(http://wp.widewallpapers.ru/2k/nature/mountains/1440x900/mountains-1440x900-009.jpg);

}

/* Add styles to the form container */
.container {
    position: absolute;
    right: 0;
    margin: 20px;
    max-width: 300px;
    padding: 16px;
    background-color: white;
}


/* Set a style for the submit button */
.btn {
    background-color: #4CAF50;
    color: white;
    padding: 16px 20px;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

</style>
</head>
<body>

<div class="bg-img">
  <form method="post">
    <div class="container">
{% if user.is_authenticated %}
    <h1><strong>Lets start!!!</strong></h1>

<div class="btn-group" role="group" aria-label="Basic outlined example">
  <a href="{% url 'selection:product_list' %}" class="btn btn-primary btn-lg">
                        Our animals=)
                    </a>
  <a href="{% url 'logout' %}" class="btn btn-primary btn-lg">
                        Logout
                    </a>
</div>

{% else %}
  <h1><strong>Hi, we will help you choose your little friend.</strong></h1>
<div class="btn-group" role="group" aria-label="Basic outlined example">
  <a href="{% url 'login' %}" class="btn btn-success">
                        login
                    </a>
  <a href="{% url 'signup' %}" class="btn btn-danger">
                        signup
                    </a>
</div>

{% endif %}
        </div>
  </form>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <style>
body {
    font-family: Arial, Helvetica, sans-serif;
background-image: url(http://wp.widewallpapers.ru/2k/nature/winter/1440x900/winter-wallpaper-1440x900-039.jpg);
}
* {box-sizing: border-box}

/* Поля ввода полной ширины */
input[type=email], input[type=password] {
  width: 30%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Установите стиль для всех кнопок */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Дополнительные стили для кнопки Отмена */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Поплавок отмена и кнопки регистрации и добавить равную ширину */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Добавление отступов к элементам контейнера */
.container {
  padding: 16px;
}

/* Снимите поплавки */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Измените стили для кнопки отмены и кнопки регистрации на дополнительных маленьких экранах */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<body>

<form method="post">
  <div class="container">
    <h1>Enter</h1>
    <p>
Please fill out the form</p>
    <hr>
      {% csrf_token %}

    {{ form.as_p }}

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>


    <div class="clearfix">
      <button type="button" class="cancelbtn">Back</button>
      <button type="submit" class="signupbtn">Sign up</button>
    </div>
  </div>
</form>


{% endblock %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>