api/urls.py
from django.urls import path, include
from .views import ProductApiView

urlpatterns = [
    path('', ProductApiView.as_view()),
]

basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', views.basket_remove, name='basket_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

store_for_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls


from django.views.generic.base import TemplateView
from django.conf import settings


#schema_view = get_schema_view(title="Store_for_all")
schema_view = get_swagger_view(title="Store_for_all")


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('selection/', include('selection.urls', namespace='selection')),
    path('orders', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls')),
    #path('schema/', schema_view),
    path('docs/', include_docs_urls(title="Store_for_all")),
    path('swagger-docs/', schema_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models

# Create your models here.

basket/forms.py
from django import forms


class BasketAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)

basket/views.py
from django.shortcuts import render
from django.conf import settings
from .forms import BasketAddProductForm

from decimal import Decimal

from selection.models import Product

from django.shortcuts import get_object_or_404, redirect


def get_basket(request):
    basket = request.session.get(settings.BASKET_ID)
    if not basket:
        basket = request.session[settings.BASKET_ID] = {}
    return basket


def basket_add(request, product_id):
    basket = get_basket(request)

    product = get_object_or_404(Product, id=product_id)
    product_id = product.id
    form = BasketAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        if product_id not in basket:
            basket[product_id] = {'quantity': 0, 'price': str(product.price)}

        if request.POST.get('overwrite_qty'):
            basket[product_id]['quantity'] = cd['quantity']
        else:
            basket[product_id]['quantity'] += cd['quantity']

        request.session.modified = True

    return redirect('basket:basket_detail')


def basket_detail(request):
    basket = get_basket(request)
    product_ids = basket.keys()
    products = Product.objects.filter(id__in=product_ids)
    temp_basket = basket.copy()
    basket_total_price = 0

    for product in products:
        basket_item = temp_basket[str(product.id)]
        basket_item['product'] = product
        basket_item['total_price'] = (Decimal(basket_item['price']) * basket_item['quantity'])
        basket_total_price = sum(Decimal(item['price']) * item['quantity'] for item in temp_basket.values())

        basket_item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': basket_item['quantity']})

    return render(request, 'basket/detail.html', {
        'basket': temp_basket.values(),
        'basket_total_price': basket_total_price
    })


def basket_remove(request, product_id):
    basket = get_basket(request)
    product_id = str(product_id)
    if product_id in basket:
        del basket[product_id]
        request.session.modified = True
    return redirect('basket:basket_detail')


def basket_clear(request):
    del request.session[settings.BASKET_ID]

templates/basket/detail.html
{% extends 'base.html' %}
{% block title %}Basket{% endblock %}
{% block content %}
    <div class="basket shadow-custom border-0 col-lg-10 mx-auto mb-3">
        <h3 class="py-2 font-weight-bold text-grey text-center">
            Your order:
        </h3>
        <div class="row justify-content-center py-2 text-center header-desc">
            <div class="col-lg-2 align-self-center">
                Product
            </div>
            <div class="col-lg-2 align-self-center">
                Description
            </div>
            <div class="col-lg-2 align-self-center">
                Availability
            </div>
            <div class="col-lg-1 align-self-center">
                Price
            </div>
            <div class="col-lg-2 align-self-center">
                Quantity
            </div>
            <div class="col-lg-3 align-self-center">
                Total price
            </div>
        </div>
        <hr class="mt-0">
        {% for item in basket %}
            {% with product=item.product %}
                <div class="row justify-content-center basket">
                    <div class="basket-item col-4 col-lg-2">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" alt=""
                                class="img-fluid rounded-0">
                        </a>
                    </div>
                    <div class="basket-item product-name col-12
col-lg-2 align-center text-center">
                        {{ product.name }}
                    </div>
                    <div class="basket-item col-12 col-lg-2 align-self-center">
                        {% if product.available %}
                            <div class="text-green mb-0 text-center">
                                Available
                            </div>
                        {% else %}
                            <div class="text-danger mb-0 text-center">
                                Not Available
                            </div>
                        {% endif %}
                    </div>
                    <div class="basket-item col-12 col-sm-3
col-lg-1 align-self-center text-center">
                        <span>${{ product.price }}</span>
                    </div>
                    <div class="basket-item col-6 col-sm-5 col-lg-2 align-self-center">
                        <form action="{% url 'basket:basket_add' product.id %}" method="post">
                            {% csrf_token %}
<span class="input-group shopping-basket">
{{ item.update_quantity_form.quantity }}
<input type="hidden" name="overwrite_qty" value="True">
<div class="input-group-append">
<button type="submit" class="btn text-white"
        data-toggle="tooltip" data-placement="top"
        title="Update">
<i class="fas fa-edit"></i>
</button>
</div>
</span>
                        </form>
                    </div>
                    <div class="basket-item col-12 col-sm-3
col-lg-2 align-self-center text-right">
                        <span>${{ item.total_price }}</span>
                    </div>

                    <div class="basket-item col-12 col-lg-1 text-right align-self-center">
                        <form action="{% url 'basket:basket_remove' product.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" data-toggle="tooltip"
                                    data-placement="top" title="Remove">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                </div>
            {% endwith %}
        {% empty %}
            <div class="align-self-center">
<span class="text-center font-weight-bold text-muted lead">
Buy something from us
</span>
            </div>
        {% endfor %}
        <hr>
        <div class="total-price-cart">
            <h4 class="row justify-content-center">
                <div class="col-5 col-lg-9 text-right text-gray">
                    Total price:
                </div>
                <div class="col-5 col-lg-2 text-right text-success">
                    ${{ basket_total_price|floatformat:2 }}
                </div>
                <div class="col-2 col-lg-1">
                </div>
            </h4>
        </div>
    </div>
    <hr>
    <div class="col-lg-10 mx-auto mb-5">
        <div class="row justify-content-end">
            <div class="col-lg-6 px-0">
                <div class="btn-group d-flex">

                    <a href="{% url 'orders:order_create' %}"
                       class="btn btn-success shadow-custom col">
                        Buy
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}